server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.neo4j.jdbc.http.HttpDriver
    name: neo4j
    password: 123456
    url: jdbc:neo4j:http://localhost:7474

mybatis:
  mapper-locations: classpath*:**/*Mapper.xml


#
#spring.data.neo4j.uri=bolt://127.0.0.1:7687
#spring.data.neo4j.username=neo4j
#spring.data.neo4j.password=123456
##spring.data.neo4j.uri=http://localhost:7474
#server.port=8080
#
#mybatis.mapper-locations=classpath*:mapper/*.xml